### ISSUE TITLE
Where is source code for aad_certhandler?

### ISSUE THREAD

**Issue by bchess** [aad-for-linux/pam_aad#25]
I realize this repo is specific to `pam_aad` so apologies but not sure where else this ticket could go. The `aadsshlogin` package installs `libnss_aad`, `pam_aad`, but also `aad_certhandler` and `aaduseradd` and `aaduserdel`. Where is the source code for these additional binaries? Particularly `aad_certhandler`

**Comment by oxr463** [comment]
Hi @bchess! I'm not familiar with those? Do you have any links to those?

**Comment by bchess** [comment]
Yeah its part of the package distribution for aadsshlogin. I'm using the deb, but here's a link to the RPM that lists contents: (See the "Files" section) https://centos.pkgs.org/8/microsoft-prod-x86_64/aadsshlogin-1.0.020810001-1.x86_64.rpm.html

**Comment by oxr463** [comment]
That is not part of aad-for-linux. If you find the source rpm maybe you can find the source URL.
