### ISSUE TITLE
Allow custom usernames (other than user principal name)

### ISSUE THREAD

**Issue by robin-wayve** [aad-for-linux/pam_aad#30]
Having an `@` in the username has caused some issues in software I'm using. I thought since `--oid` (object ID) is a separate flag to the `LOGIN` argument, that I'd be able to make my login whatever I wanted but instead I get
```
aaduseradd: invalid user UPN 'robin'. Use useradd instead.
```

**Comment by oxr463** [comment]
The `aaduseradd` utility is not part of this project. We curently only provide a PAM module, an NSS module, and an OpenVPN plugin.

Relates to https://github.com/aad-for-linux/pam_aad/issues/25
